config/routes.rb
Submarine::Application.routes.draw do
  resources :questions

  if feature_active? :persist_present_demo
    root :to => 'navigation#index', :as => 'index'
    get 'contact_page' => 'questions#new', :as => 'contact_page'
  else
    root :to => 'issues#new_issues_list', :as => 'index'
    get 'contact_page' => 'navigation#contact_page', :as => 'contact_page'
  end
  post 'change_list' => 'issues#change_list', :as => 'change_list'
  post 'finish_issue/:id' => 'issues#finish_issue', :as => 'finish_issue'
  post 'activate_issue/:id' => 'issues#activate_issue', :as => 'activate_issue'
  get 'finished_issues' => 'issues#finished_issues_list', :as => 'finished_issues'

  get 'new_issues' => 'issues#new_issues_list', :as => 'new_issues'

  get 'impressum' => 'navigation#impressum', :as => 'impressum'
  get 'finished'=> 'questions#finished', :as => 'finished'

  put 'issues/:id' => 'issues#status_handler', :as => 'status_handler'

  resources :issues do
    member { get 'file_attachment' }
  end
  resources :projects do
    member { get 'project_icon' }
  end
  resources :bugs, :controller => 'issues'
  resources :tasks, :controller => 'issues'
  resources :user_stories, :controller => 'issues'
  resources :document, :controller => 'issues'
end

app/models/issue.rb
require 'helper/lock_version_helper'

class Issue < ActiveRecord::Base
  belongs_to :project
  belongs_to :predecessor, :class_name => 'Issue', :foreign_key => :predecessor_id
  belongs_to :backlog

  # next item in the list
  has_one :descendant, :class_name => 'Issue', :foreign_key => :predecessor_id

  mount_uploader :file_attachment, FileAttachmentUploader

  validates :name, :type, :project, :description, presence: true

  before_destroy :close_gap
  before_save :set_lock
  after_save :update_lock

  scope :first_in_list, -> { where(predecessor_id: nil) }
  scope :last_in_list, -> { find_by_sql("select * from issues a where not exists (select * from issues b where b.predecessor_id = a.id)") }

  def self.children_type_names
    ['UserStory', 'Task', 'Bug', 'Document']
  end

  def formatted_story_points
    if self.story_points
      self.story_points == 0.5 ? '0.5' : story_points.to_i.to_s
    else
      ''
    end
  end

  def finish
    move_to Backlog.finished_backlog
  end

  def activate
    update_attributes(examined_at: DateTime.now, finished_at: nil, done_at: nil, planned_at: nil, ready_to_finish: false)
    move_to Backlog.backlog
  end

  def finished?
    backlog == Backlog.finished_backlog
  end

  def in_sprint?
    backlog == Backlog.sprint_backlog
  end

  def in_new_issue_list?
    backlog == Backlog.new_issues_list
  end

  def in_backlog?
    backlog == Backlog.backlog
  end

  def done!
    update_attributes(ready_to_finish: true, done_at: DateTime.now)
  end

  def doing!
    update_attributes(planned_at: DateTime.now, ready_to_finish: false, done_at: nil)
  end

  def done?
    self.ready_to_finish == true
  end

  def close_gap
    descendant = self.descendant
    if descendant
      descendant.predecessor_id = self.predecessor_id
      descendant.save!
    end
  end

  def move_to(backlog, options={}) #!ref!
    transaction do
      #remove issue from linked list
      #by connecting predecessor and descendant
      if self.descendant
        descendant = self.descendant
        self.descendant = nil
        descendant.predecessor = self.predecessor
        descendant.save!
      end

      log_move_changes(backlog)

      self.predecessor = nil
      self.backlog = nil
      self.save!

      #insert issue into linked list
      #by setting new predecessor and his descendant
      if options.has_key? :new_predecessor
        new_predecessor = options[:new_predecessor]
        new_predecessor.reload

        raise "Backlog of predecessor does not match the passed backlog" if new_predecessor.backlog != backlog

        new_descendant = new_predecessor.descendant
        if new_descendant && new_descendant != self
          new_descendant.predecessor = self
          new_descendant.save!
        end
        self.predecessor = new_predecessor
      else
        self.predecessor = nil
        new_descendant = Issue.where("backlog_id = :backlog_id AND predecessor_id IS NULL AND id != :issue_id", backlog_id: backlog.id, issue_id: self.id ).first
        if new_descendant
          new_descendant.predecessor = self
          new_descendant.save!
        end
      end

      self.backlog = backlog if self.backlog != backlog
      self.save!
    end
  end

  def set_lock
    if LockVersionHelper::lock_version == nil
      return
    end

    self.lock_version = LockVersionHelper::lock_version[self.id.to_s]
  end

  def update_lock
    if LockVersionHelper::lock_version == nil
      return
    end

    LockVersionHelper::lock_version[self.id.to_s] = self.lock_version
  end

  private

  def log_move_changes new_list_type
    case new_list_type

    when Backlog.backlog
      if self.in_new_issue_list? #comes from new_issues_list
        update_attributes(examined_at: DateTime.now)
      elsif self.in_sprint? #comes from sprint_backlog
        update_attributes(examined_at: DateTime.now, planned_at: nil)
      end
    when Backlog.new_issues_list
      update_attributes(examined_at: nil)
    when Backlog.sprint_backlog
      update_attributes(planned_at: DateTime.now)
    end
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:edit, :file_attachment, :destroy, :finish_issue, :activate_issue, :status_handler, :show]

  def index
    @backlog_issues = sorted_list(Backlog.backlog.first_issue)
    @sprint_issues = sorted_list(Backlog.sprint_backlog.first_issue)

    extension_whitelist
  end

  def new
    @issue = Issue.new
    extension_whitelist
    prepare_form
  end

  def edit
    extension_whitelist
    prepare_form
  end

  def create
    if params[:issue]
      type = params[:issue][:type]
      if Issue.children_type_names.include? type
        model_class = Kernel.const_get type
        params[:issue][:story_points] = nil if params[:issue][:story_points] == 'unknown'
        @issue = model_class.new(issue_params(:issue))
      end
    else
      types = Issue.children_type_names
      @issue = nil
      types.each do |t|
        @type = t.gsub(/(.)([A-Z])/,'\1_\2').downcase
        if params[@type.to_sym]
          model_class = Kernel.const_get t
          @issue = model_class.new(issue_params(@type.to_sym))
          params[@type.to_sym][:story_points] = nil if params[@type.to_sym][:story_points] == 'unknown'
          break
        end
      end
    end

    if @issue
      old_first_issue = Backlog.new_issues_list.first_issue
      Backlog.new_issues_list.issues << @issue
      @issue.predecessor_id = nil
    end

    if @issue && @issue.save
      if old_first_issue
        old_first_issue.predecessor_id = @issue.id
        old_first_issue.save!
      end

      redirect_to new_issues_path, notice: t('issue.successful_added')
    else
      extension_whitelist
      prepare_form
      render action: "new"
    end
  end

  def update
    types = Issue.children_type_names
    @issue = nil

    types.each do |t|
      @type = t.gsub(/(.)([A-Z])/,'\1_\2').downcase
      if params[@type]
        @issue = Issue.find(params[:id])
        new_type = params[@type].delete :type
        @issue[:type] = new_type
        break
      end
    end

    params[@type][:story_points] = nil if params[@type][:story_points] == 'unknown'

    if @issue && @issue.update(issue_params(@type))
      redirect_to (@issue.in_new_issue_list? ? new_issues_path : issues_path), notice: t('issue.successful_edited')
    else
      prepare_form
      @issue.errors[:base] << t('issue.edited')
      render action: "edit"
    end

  rescue ActiveRecord::StaleObjectError
    prepare_form
    @issue.errors[:base] << t('issue.edited')
    render action: "edit"
  end

  def destroy
    @issue.destroy
    redirect_to (@issue.in_new_issue_list? ? new_issues_path : issues_path), notice: t('issue.successful_deleted')
  end

  # moves backlog_item from one backlog to the other backlog
  #
  # @param [JSON-string] params[] moved item, backlog list, sprint backlog list
  # example:
  # {"moved_issue_id" => "3",
  # "backlog_list" => [[0] "4",[1] "1",[2] "2"],
  # "sprint_backlog_list" => [[0] "3"]}
  def change_list
    moved_issue = Issue.find params[:moved_issue]
    predecessor = params[:predecessor] ? Issue.find(params[:predecessor]) : nil
    backlog = Backlog.find_by(name: params[:backlog])
    LockVersionHelper::lock_version = params[:lock_versions]

    if predecessor
      moved_issue.move_to backlog, new_predecessor: predecessor
    else
      moved_issue.move_to backlog
    end

    moved_issue.ready_to_finish = false
    moved_issue.save
    render :json => LockVersionHelper::lock_version
  ensure
    LockVersionHelper::lock_version = nil
  end

  def finish_issue
    extension_whitelist

    @issue.finish
    @issue.finished_at = DateTime.now
    @issue.save

    redirect_to issues_path
  end

  def finished_issues_list
    extension_whitelist
    @finished_issues = sorted_list(Backlog.finished_backlog.first_issue)
  end

  def new_issues_list
    @new_issues = sorted_list(Backlog.new_issues_list.first_issue)
    @backlog_issues = sorted_list(Backlog.backlog.first_issue)
    extension_whitelist

    if Project.all.empty?
      flash.now[:notice] = t('issue.no_issue')
    end
  end

  def show
  end

  def activate_issue
    @issue.activate

    redirect_to finished_issues_path
  end

  def status_handler
    if @issue.done?
      @issue.doing!
    else
      @issue.done!
    end

    redirect_to issues_path
  end

  def extension_whitelist
    @extension_whitelist = ['.jpg', '.jpeg', '.png', '.bmp', '.gif']
  end

  def file_attachment
    send_data @issue.file_attachment.read, filename: @issue.file_attachment.file.filename
  end

  private

  def set_issue
    @issue = Issue.find(params[:id])
  end

  def prepare_form
    @projects = Project.all.collect do |project|
      [project.name, project.id, project.project_icon_url]
    end
    a_number = 0
    @types = Issue.children_type_names.map do |name|
      name
    end
    @story_points = ['unknown', 0, 0.5, 1, 2, 3, 5, 8, 13, 20]
  end

  def sorted_list element
    issues = []

    if element
      issues << element

      while element.descendant do
        element = element.descendant
        issues << element
      end
    end

    issues
  end

  def issue_params type
    params.require(type).permit("name", "description", "story_points", "project_id", "lock_version", "file_attachment")
  end

end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.slim
= form_for(@issue) do |f|
  - if @issue.errors.any?
    div#error_explanation
      h2
        = t('errors_occured')
      ul
        - if @issue.errors[:base] && @issue.errors[:base][0]
          li
            = @issue.errors[:base][0]
        - @issue.errors.messages.each do |key, msg|
          li
            - @issue.errors.delete :base
            h3
              = t 'activerecord.attributes.issue.' + key.to_s
            = msg[0]
  div.field
    = f.label :name
    = f.text_field :name

  div.field
    = f.label :description
    = f.text_area :description, rows: 10

  div.field.sp_radio_images.image_select
    = f.label :story_points
    div
      - @story_points.each do |number|
        div*{'class' => "radio_image sp_#{number.to_s.gsub(".", "_")}", 'data-sp-value' => "#{number}"}
          = image_tag "#{image_path "sp_#{number}_light.png"}", 'data-img_heavy' => "#{image_path "sp_#{number}_heavy.png"}", 'data-img_light' => "#{image_path "sp_#{number}_light.png"}"
      = f.hidden_field :story_points, :value => (@issue.story_points ? @issue.formatted_story_points : @story_points[0])

  div.field.type_radio_images.image_select
    = f.label :type
    - @types.each do |type|
      div*{'class' => "radio_image #{type.downcase}", 'data-type' => "#{type}"}
        = image_tag "#{type.downcase}_light.png", :title => "#{type.titleize}", 'data-img_heavy' => image_path("#{type.downcase}_heavy.png"), 'data-img_light' => image_path("#{type.downcase}_light.png")
    = f.hidden_field :type, :value => (@issue.type ? @issue.type : @types[0])

  div.field.project_radio_images.image_select
    = f.label :project_id
    - @projects.each do |project|
      div*{'class' => "radio_image #{project[0].downcase}", 'data-project-id' => "#{project[1]}"}
        - if project[2].nil?
          = image_tag "fallback/default.png"
        - else
          = image_tag(project[2])
    = f.hidden_field :project_id, :value => (@issue.project_id ? @issue.project_id : @projects[0][1])
    = f.hidden_field :lock_version, :value => (@issue.lock_version)

  div.field
    = f.label 'Anhang'
    = f.file_field :file_attachment
    - if @issue.file_attachment? == true && @issue.valid?
      = link_to image_tag('box1.png', {:class => 'download_file_attachment'}), @issue.file_attachment.url

  div.field
    - if @issue.file_attachment? == true && @issue.valid?
      = f.hidden_field :file_attachment_cache
      - if @extension_whitelist.include?(File.extname(@issue.file_attachment.file.original_filename))
        = f.label 'Vorschau'
        img*{'src' => "file_attachment", 'class' => 'issue_image_file' }
      - else
        = f.label 'Vorschau'
        = File.basename(@issue.file_attachment.file.original_filename)

  div.field
    - if feature_active? :delete_project_icon_via_button
      - if @issue.file_attachment? == true
        = f.label 'Anhang löschen?'
        = f.check_box :remove_file_attachment

  div.actions
    = image_submit_tag "btn_save.png"
    = link_to request.referer, class: "button finish_edit" do
      = image_tag "btn_cancel.png"

app/views/issues/_list.html.slim
article.log*{'id' => list_type}
  ul.list_header
    = render partial: 'list_header', locals: { list_type: list_type }

  ul.connectedSortable*{'id' => list_type + "_list"}
    - list_items.each do |item|
      li *{'data-id' => item.id, 'id' => "#{item.id}", 'data-story_points' => item.formatted_story_points, 'data-lock-version' => item.lock_version}

        div.visuals_left
          div.project_logo
            - if item.project.project_icon.file.nil?
              = image_tag "fallback/default.png"
            - else
              = image_tag(item.project.project_icon.url)
          div.issue_type
            = image_tag("#{item.type.downcase}_heavy.png")
          div.issue_story_points
            = image_tag("sp_#{item.formatted_story_points}_heavy.png", :size => "22x22") if item.story_points

        div.visuals_right
          div*{ 'class' => "#{list_type == 'sprint_backlog' ? 'sprint_controls controls_container' : 'controls_container' }"}
            div.controls
              - if list_type == 'sprint_backlog'
                = link_to edit_issue_path(item), :class => 'edit_issue',:title => t('issue.edit') do
                  = image_tag("edit.png")

                = link_to finish_issue_path(item), :method => :post, :class => 'finish_issue', :title => t('issue.finish') do
                  = image_tag("finish_issue.png")

                - if item.ready_to_finish == true
                  = link_to status_handler_path(item), :method => 'put' , :class => "set_issue_ready" do
                    = image_tag("issue_ready.png", :title => t('issue.ready'))
                - else
                  = link_to status_handler_path(item), :method => 'put' , :class => "set_issue_ready" do
                    = image_tag("issue_in_progress.png", :title => t('issue.pending'))

                = link_to item, :method => :delete, :class => 'delete_issue', :style => 'display: none;', :title => t('issue.delete') do
                  = image_tag("delete.png")

                = link_to issue_path(item), class: 'show_issue', title: t('issue.show') do
                  = image_tag('document.png')

              - if list_type == 'backlog'
                = link_to edit_issue_path(item), :class => 'edit_issue',:title => t('issue.edit') do
                  = image_tag("edit.png")

                = link_to finish_issue_path(item), :method => :post, :class => 'finish_issue', :style => 'display: none;', :title => t('issue.finish') do
                  = image_tag("finish_issue.png")

                = link_to item, :method => :delete, :class => 'delete_issue', :title => t('issue.delete') do
                  = image_tag("delete.png")

                - if item.ready_to_finish == true
                  = link_to status_handler_path(item), :method => 'put' , :class => "set_issue_ready", :style => 'display: none;' do
                    = image_tag("issue_ready.png", :title => t('issue.ready'))
                - else
                  = link_to status_handler_path(item), :method => 'put' , :class => "set_issue_ready", :style => 'display: none;' do
                    = image_tag("issue_in_progress.png", :title => t('issue.pending'))

                = link_to issue_path(item), class: 'show_issue', title: t('issue.show') do
                  = image_tag('document.png')

              - if list_type == 'finished_issues'
                = link_to activate_issue_path(item), :method => :post, :class => 'activate_issue', :title => t('issue.activate') do
                  = image_tag("activate_issue.png")
                = link_to issue_path(item), class: 'show_issue', title: t('issue.show') do
                  = image_tag('document.png')

              - if list_type == 'new_issues'
                = link_to edit_issue_path(item), class: 'edit_issue', title: t('issue.edit') do
                  = image_tag('edit.png')

                = link_to finish_issue_path(item), :method => :post, :class => 'finish_issue', :style => 'display: none;', :title => t('issue.finish') do
                  = image_tag("finish_issue.png")

                = link_to item, :method => :delete, class: 'delete_issue', title: t('issue.delete') do
                  = image_tag('delete.png')

                - if item.ready_to_finish == true
                  = link_to status_handler_path(item), :method => 'put' , :class => 'set_issue_ready', :style => 'display: none;' do
                    = image_tag("issue_ready.png", :title => t('issue.ready'))
                - else
                  = link_to status_handler_path(item), :method => 'put' , :class => 'set_issue_ready', :style => 'display: none;' do
                    = image_tag("issue_in_progress.png", :title => t('issue.pending'))

                = link_to issue_path(item), class: 'show_issue', title: t('issue.show') do
                  = image_tag('document.png')

        div.issue_line_title
          div.issue_id
            = "##{item.id}"
          div.issue_name
            = item.name

        div.issue_line
          div.description.short
            = simple_format(item.description)

            - if item.file_attachment? == true
              - if @extension_whitelist.index(File.extname(item.file_attachment.file.original_filename))
                = link_to( image_tag('box1.png', {:class => 'download_file'}), "issues/#{item.id}/file_attachment", {:class=>"swimbox"})
              - else
                = link_to( image_tag('box1.png', {:class => 'download_file'}), "issues/#{item.id}/file_attachment")

            div.date_at_timestamp
              - case list_type
              - when 'new_issues'
                p.timestamp = t('issue.created_at')
                = to_local(item.created_at)
              - when 'backlog'
                p.timestamp = t('issue.examined_at')
                = to_local(item.examined_at)
              - when 'sprint_backlog'
                - if item.done?
                  p.timestamp = t('issue.done_at')
                  = to_local(item.done_at)
                - else
                  p.timestamp = t('issue.planned_at')
                  = to_local(item.planned_at)
              - when 'finished_issues'
                p.timestamp = t('issue.finished_at')
                = to_local(item.finished_at)

javascript:
  SUBMARINE.sprint_count = "#{@sprintbacklog_count}";

app/views/issues/_list_header.html.slim
ul.list_header
  - case list_type
  - when 'sprint_backlog'
    li
      = t('sprint_backlog')
    li#story_points_sum.no_js
      span
      = image_tag 'sp_sum_0.5_heavy.png', :id => 'half_story_point'
      = image_tag 'sp_0.5_heavy.png', :id => 'half_story_point_small'

  - when 'backlog'
    li = t('backlog_list')

  - when 'finished_issues'
    li
      = t 'finished_issues'
    li#btn_in_header
      = link_to issues_path, :title => t('backlogs') do
        = image_tag('show_backlogs.png')

  - when 'new_issues'
    li = t('new_issues')
    li#btn_in_header
      - unless Project.all.empty?
        = link_to new_issue_path,:title => t('issue.new') do
          = image_tag('new.png')

app/views/issues/edit.html.slim
section#main
	article.issue_form
		ul.form_header
			li
				= "##{@issue.id} "
				= t'issue.edit'
		= render 'form'

javascript:
	$(document).ready(function(){
  	$("div.sp_radio_images div.radio_image").click(SUBMARINE.check_sp_radio_image);
  	$("div.type_radio_images div.radio_image").click(SUBMARINE.check_type_radio_image);
  	$("div.project_radio_images div.radio_image").click(SUBMARINE.check_project_radio_image);

  	SUBMARINE.preselect_radio_images('#{@issue.formatted_story_points}', '#{@issue.type}', '#{@issue.project.name}');
	});

app/views/issues/finished_issues_list.html.slim
section#finished_issues_section
	= render :partial => "list", :locals => {:list_type => 'finished_issues', :list_items => @finished_issues}
	javascript:
		$("ul > li > div > div.description").bind("click", SUBMARINE.toggleDescription);
		$("ul.connectedSortable > li").mouseenter(SUBMARINE.showControls).mouseleave(SUBMARINE.hideControls);

app/views/issues/index.html.slim
meta name="keywords" content="scrum, backlog, sprint, user stories, tool"
meta name="description" content="Sie wollen ein virtuelles Backlog, das mehrere Projekte unterstützt? Dann probieren Sie es mit submarine. Eine kostenlose Online-Demo steht Ihnen hier zur Verfügung."

section#main
  = render :partial => "list", :locals => {:list_type => 'backlog', :list_items => @backlog_issues}
  = render :partial => "list", :locals => {:list_type => 'sprint_backlog', :list_items => @sprint_issues}

  div#refresh-dialog.no_js*{'title' => 'notification'}
    = t 'issue.errors.data_staled'

  javascript:

    $(function() {
      $('.no_js').removeClass('no_js');

      $("#sprint_backlog_list, #backlog_list").sortable({
        connectWith: ".connectedSortable",
        start: function(event,ui) { $(ui.item).addClass("dragging"); },
        stop: SUBMARINE.changeListHandler
      }).disableSelection();

      SUBMARINE.showStoryPointsSum();

      $("ul > li > div > div.description").bind("click", SUBMARINE.toggleDescription);

      $("#refresh-dialog").dialog({
        autoOpen: false,
        closeText: '',
        modal: true,
        resizeable: false,
        dragable: false,
        minHeight: null,
        buttons: {
          OK: function() {
            location.reload();
          }
          },
          close: function(event, ui) { location.reload(); }
        });
      }
    );
    SUBMARINE.changeListURL = #{change_list_path.to_json.html_safe};

app/views/issues/new.html.slim
section#main
	article.issue_form
		ul.form_header
			li = t 'issue.new'
		= render 'form'

	javascript:
		$(document).ready(function(){
  		$("div.sp_radio_images div.radio_image").click(SUBMARINE.check_sp_radio_image);
  		$("div.type_radio_images div.radio_image").click(SUBMARINE.check_type_radio_image);
  		$("div.project_radio_images div.radio_image").click(SUBMARINE.check_project_radio_image);

  		SUBMARINE.preselect_radio_images('#{@issue.formatted_story_points}', '#{@types[0].downcase}', '#{@projects[0][0].downcase}');
		});

app/views/issues/new_issues_list.html.slim
section#main
  = render :partial => 'list', :locals => {:list_type => 'new_issues', :list_items => @new_issues}
  = render :partial => "list", :locals => {:list_type => 'backlog', :list_items => @backlog_issues}

  div#refresh-dialog.no_js*{'title' => 'notification'}
    = t 'issue.errors.data_staled'

  javascript:

    $(function() {
      $('.no_js').removeClass('no_js');

      $("#backlog_list, #new_issues_list").sortable({
        connectWith: ".connectedSortable",
        start: function(event,ui) { $(ui.item).addClass("dragging"); },
        stop: SUBMARINE.changeListHandler
      }).disableSelection();

      $("ul > li > div > div.description").bind("click", SUBMARINE.toggleDescription);

      $("#refresh-dialog").dialog({
        autoOpen: false,
        closeText: '',
        modal: true,
        resizeable: false,
        dragable: false,
        minHeight: null,
        buttons: {
          OK: function() {
            location.reload();
          }
          },
          close: function(event, ui) { location.reload(); }
        });
      }
    );
    SUBMARINE.changeListURL = #{change_list_path.to_json.html_safe};

app/views/issues/show.html.slim
section#main
  article.issue_form
    ul.form_header
      li = t('issue.show')

    .field
      label = t('activerecord.attributes.issue.name')
      .value = @issue.name

    .field
      label = t('activerecord.attributes.issue.description')
      .value = @issue.description

    .field
      label = t('activerecord.attributes.issue.story_points')
      .value = @issue.story_points

    .field
      label = t('activerecord.attributes.issue.type')
      .value = @issue.type

    .field
      label = t('activerecord.attributes.issue.project_id')
      .value = @issue.project.name

    h4.history = t('history')

    .field
      .history-label = to_local(@issue.created_at)
      .value = t('issue.state_created')

    - if @issue.examined_at
      .field
        .history-label = to_local(@issue.examined_at)
        .value = t('issue.state_examined')

    - if @issue.planned_at
      .field
        .history-label = to_local(@issue.planned_at)
        .value = t('issue.state_planned')

    - if @issue.done_at
      .field
        .history-label = to_local(@issue.done_at)
        .value = t('issue.state_done')

    - if @issue.finished_at
      .field
        .history-label = to_local(@issue.finished_at)
        .value = t('issue.state_finished')

    div.actions.back
      - if @issue.finished?
        = link_to finished_issues_path, class: 'button finish_edit' do
          = image_tag 'btn_back.png'

      - elsif @issue.in_sprint? || @issue.in_backlog?
        = link_to issues_path, class: 'button finish_edit' do
          = image_tag 'btn_back.png'

      - else
        = link_to new_issues_path, class: 'button finish_edit' do
          = image_tag 'btn_back.png'