config/routes.rb
Submarine::Application.routes.draw do
  resources :questions

  if feature_active? :persist_present_demo
    root :to => 'navigation#index', :as => 'index'
    get 'contact_page' => 'questions#new', :as => 'contact_page'
  else
    root :to => 'issues#new_issues_list', :as => 'index'
    get 'contact_page' => 'navigation#contact_page', :as => 'contact_page'
  end
  post 'change_list' => 'issues#change_list', :as => 'change_list'
  post 'finish_issue/:id' => 'issues#finish_issue', :as => 'finish_issue'
  post 'activate_issue/:id' => 'issues#activate_issue', :as => 'activate_issue'
  get 'finished_issues' => 'issues#finished_issues_list', :as => 'finished_issues'

  get 'new_issues' => 'issues#new_issues_list', :as => 'new_issues'

  get 'impressum' => 'navigation#impressum', :as => 'impressum'
  get 'finished'=> 'questions#finished', :as => 'finished'

  put 'issues/:id' => 'issues#status_handler', :as => 'status_handler'

  resources :issues do
    member { get 'file_attachment' }
  end
  resources :projects do
    member { get 'project_icon' }
  end
  resources :bugs, :controller => 'issues'
  resources :tasks, :controller => 'issues'
  resources :user_stories, :controller => 'issues'
  resources :document, :controller => 'issues'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :issues, :dependent => :destroy

  validates :name, :length => { :maximum => 50 }
  validates_presence_of :name
  mount_uploader :project_icon, ProjectIconUploader

  default_scope { order('name ASC') }
end

app/controllers/projects_controller.rb
# encoding: utf-8
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy, :project_icon]

  def index
    @projects = Project.all
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to projects_path, :notice => t('project.successful_added')
    else
      render :action => 'new'
    end
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path, :notice => t('project.successful_edited')
    else
      render :action => 'edit'
    end
  end

  def project_icon
    send_data @project.project_icon.read, filename: @project.project_icon.file.filename
  end

  def destroy
    if Issue.where('project_id = ?', @project.id).where('backlog_id != ?', Backlog.finished_backlog).count == 0
      @project.destroy
      redirect_to projects_path, :notice => t('project.successful_deleted')
    else
      redirect_to projects_path, :notice => t('project.not_destroyable')
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit("name", "project_icon_cache", "project_icon", "remove_project_icon")
  end
end

app/views/projects/_form.html.slim
= form_for(@project) do |x|
  - if @project.errors.any?
    div#error_explanation
      h2 = t('errors_occured')
      ul
        - @project.errors.full_messages.each do |msg|
          li = msg
  div.field
    = x.label :name
    = x.text_field :name
    = x.hidden_field :project_icon_cache
  div.field
    p.project_text_label = t('project.notice')
  div.field
    = x.file_field :project_icon
  div.field
    - if @project.project_icon?
      = image_tag(@project.project_icon_url, {:class => 'form_image'})
    - else
      div.form_field
        p.project_text_label = t('project.default_icon')
        = image_tag('fallback/default.png', {:class => 'form_image'})
  div.field
    - if feature_active? :delete_project_icon_via_button
      - unless @project.project_icon?
        = x.label 'Icon löschen?'
        = x.check_box :remove_project_icon
  div.actions
    = image_submit_tag 'btn_save.png'
    = link_to projects_path, class: 'button finish_edit' do
      = image_tag 'btn_cancel.png'

app/views/projects/_list.html.slim
div.projects_main
  article.log
    ul.list_header
      li = t('project.all')
      li#btn_in_header
        = link_to new_project_path, :class => 'edit_project', :title => t('project.new') do
          = image_tag('new.png')

    table.projects_table = render @projects

app/views/projects/_project.html.slim
tr.list_row
  td.image
    - if project.project_icon.file.nil?
      = image_tag 'fallback/default.png'
    - else
      = image_tag(project.project_icon)
  td.name = project.name
  td.action
    = link_to image_tag('edit.png', title: t('project.edit')), edit_project_path(project)
  td.action
    = link_to project, :method => :delete, :title => t('project.delete'), :confirm => 'Sind Sie Sicher das Sie dieses Projekt Löschen wollen?' do
      = image_tag('delete.png')

app/views/projects/edit.html.slim
div.projects_main
  div.project_form
    ul.form_header
      li = t('project.edit')
    = render :partial => 'form'

app/views/projects/index.html.slim
section#main
  = render :partial => 'list'

app/views/projects/new.html.slim
div.projects_main
  div.project_form
    ul.form_header
      li = t('project.new')
    = render :partial => 'form'