config/routes.rb
Submarine::Application.routes.draw do
  resources :questions

  if feature_active? :persist_present_demo
    root :to => 'navigation#index', :as => 'index'
    get 'contact_page' => 'questions#new', :as => 'contact_page'
  else
    root :to => 'issues#new_issues_list', :as => 'index'
    get 'contact_page' => 'navigation#contact_page', :as => 'contact_page'
  end
  post 'change_list' => 'issues#change_list', :as => 'change_list'
  post 'finish_issue/:id' => 'issues#finish_issue', :as => 'finish_issue'
  post 'activate_issue/:id' => 'issues#activate_issue', :as => 'activate_issue'
  get 'finished_issues' => 'issues#finished_issues_list', :as => 'finished_issues'

  get 'new_issues' => 'issues#new_issues_list', :as => 'new_issues'

  get 'impressum' => 'navigation#impressum', :as => 'impressum'
  get 'finished'=> 'questions#finished', :as => 'finished'

  put 'issues/:id' => 'issues#status_handler', :as => 'status_handler'

  resources :issues do
    member { get 'file_attachment' }
  end
  resources :projects do
    member { get 'project_icon' }
  end
  resources :bugs, :controller => 'issues'
  resources :tasks, :controller => 'issues'
  resources :user_stories, :controller => 'issues'
  resources :document, :controller => 'issues'
end

app/controllers/navigation_controller.rb
class NavigationController < ApplicationController
  def contact_page
  end


  def impressum
  end
end

app/views/navigation/contact_page.html.slim
meta name="keywords" content="scrum, backlog, sprint, user stories, tool, contact"
section.contact_data
  article#contact_data
    h2 Noch Fragen? Her damit!
    - form_for @question do |q|
      = q.label :betreff
      = q.text_field :betreff
      = q.label :question
      = q.text_field :question
      = q.label :email
      = q.text_field :email
      = q.submit
    input*{'type' => "button", 'value' => "Absenden"}
    = link_to "Zurück zur Hauptseite", index_url
  span
    | &nbsp;

app/views/navigation/impressum.html.slim
section#impressum
  h2 Impressum
  article#contact_information
    p
      | softwareinmotion gmbh<br>
      | software / design / management<br>
      | Marktplatz 1<br>
      | D-73660 Urbach
    p
      | Telefon +49(0)7181 / 98590-0<br>
      | Telefax +49(0)7181 / 98590-50<br>
      | info@softwareinmotion.de
    p
      = link_to "www.softwareinmotion.de", "http://www.softwareinmotion.de"

  article#legal_information
    p
      | Allein vertretungsberechtigter Geschäftsführer: Stephan&nbsp;Brunnet
    p
      | Registergericht: Amtsgericht Stuttgart<br>
      | Registernummer: HRB 738259<br>
      | Sitz der Gesellschaft: Urbach
    p
      | Umsatzsteueridentifikationsnummer gemäß §27a<br>
      | Umsatzsteuergesetz: DE269892410
    p
      | Inhaltlich verantwortlich gemäß §10 Absatz 3 MDStV:<br>
      | Stephan Brunnet (Anschrift wie oben)
    p
      | Konzeption und Gestaltung: softwareinmotion gmbh
    p
      | Copyright:<br>
      | Website-Design, Texte und Grafiken sind urheberrechtlich geschützt. (c) softwareinmotion gmbh 2012. Alle Rechte vorbehalten. Das Herunterladen und die Speicherung auf Datenträger, das Einstellen in ein eigenes oder fremdes Internetangebot, das Bereitstellen für den öffentlichen Zugriff sowie jede sonstige Vervielfältigung, Bearbeitung, Verbreitung oder öffentliche Wiedergabe der auf dieser Website verfügbaren Materialien bzw. Informationen sind nur in den engen Grenzen des Urheberrechtsgesetzes oder mit vorheriger schriftlicher Zustimmung von softwareinmotion gmbh gestattet.
    p
      | Haftungsausschluss:<br>
      | Trotz sorgfältiger inhaltlicher Kontrolle übernehmen wir keine Haftung für die Inhalte externer Links. Für den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber verantwortlich.
    p
      | softwareinmotion gmbh bzw. der Autor/Administrator übernimmt keinerlei Gewähr für die Aktualität, Korrektheit, Vollständigkeit oder Qualität der bereitgestellten Informationen.
    p
      | Kein Teil dieser Publikation darf ohne ausdrückliche schriftliche Genehmigung des Herausgebers in irgendeiner Form reproduziert oder unter Verwendung elektronischer Systeme verarbeitet, vervielfältigt oder verbreitet werden. Die geltenden gesetzlichen und postalischen Bestimmungen bei Erwerb, Errichtung und Inbetriebnahme von elektronischen Geräten sowie Sende- und Empfangseinrichtungen sind zu beachten.

    = link_to "Zurück zur Hauptseite", index_url
  p.clear

app/views/navigation/index.html.slim
meta name="keywords" content="scrum, backlog, sprint, user stories, tool"
meta name="description" content="submarine ist ein Scrum-Tool für Backlogs. Es unterstützt Sie bei der Planung ihrer Sprints."
section
  div*{'style' => "postion: relative"}
    div#ilike
      | <iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com/scrumbacklog&amp;layout=button_count&amp;show_faces=true&amp;width=450&amp;action=like&amp;colorscheme=light&amp;height=80" allowTransparency="true" marginheight="0" marginwidth="0" frameborder="0"></iframe>
    = image_tag "rahmen01.gif"
  div*{'style' => "position: relative"}
    h2 submarine - Ein Scrum-Tool für Backlogs
    div*{'id' => "post_it", 'style' => "top: -50px; right: -225px;  z-index: 2; position: absolute; "}
      h3 Was kann submarine alles?
      ul#feature_list
        li Aufgaben mehrerer Projekte in einem Backlog
        li Bearbeitung von Tasks, User Stories und Bugs
        li Priorisieren von Aufgaben
        li Verschieben der Aufgaben in den aktuellen Sprint
        li Abschließen und Archivieren von Aufgaben des aktuellen Sprints
        li Reaktivieren abgeschlossener Aufgaben
        li Automatische Summenberechnung
    div
      article#left_article
        p Sie denken sich jetzt vielleicht: "Noch ein Scrum-Tool? Ist das wirklich notwendig?" Wir sagen: "Ja!". submarine ist nicht einfach ein Scrum-Tool, sondern ein Werkzeug, das vor allem bei der Sprint-Planung unterstützt. Dafür bietet submarine ein priorisiertes Backlog sowie eines für den aktuellen Sprint. Nicht mehr, aber auch nicht weniger.

        = link_to( image_tag("th_backlog.png",  :class =>  "img-rounded"), "/assets/backlog.png", {:class=>"swimbox"})

        h1 Wieso sollte ich submarine benutzen?
        p Sie haben schon das ein oder andere Scrum-Tool verwendet? Die vielen Funktionen machen es zu unübersichtlich? Oder haben Sie bei einem reinen Software-Tool des Öfteren vergessen den Status einzelner Aufgaben aktuell zu halten?
        div
          = link_to( image_tag("th_sprint_backlog.png") ,"/assets/sprint_backlog.png", {:class=>"swimbox"})
      article#right_article
        p submarine ist anders. Es unterstützt die Verwendung eines physischen Scrum-Boards für den aktuellen Sprint einerseits und bietet ein übersichtliches virtuelles Backlog andererseits. Dadurch kann das Sprint Planning Meeting quasi überall durchgeführt werden. Im Sprint Review können außerdem alle bearbeiteten Aufgaben direkt als abgeschlossen markiert werden.

        = link_to( image_tag("th_new_backlog_entry.png") ,"/assets/new_backlog_entry.png", {:class=>"swimbox"})

        p Falls wir Sie neugierig gemacht haben sollten, dann können Sie submarine gleich online ausprobieren. Sie brauchen sich dafür nirgends anzumelden und nichts zu installieren. Die Demo ist kostenlos - eine für alle Internetbenutzer öffentlich zugängliche Version von submarine.

        = link_to "Ausprobieren", '#', :class => "button demo inactive", :title => 'Zur Demo'

        javascript:
          $(function() {
            $('a.button.demo.inactive')
            .removeClass('inactive')
            .attr('href', '#{issues_path}');
          });
        noscript
          p Bitte aktivieren Sie JavaScript, wenn Sie submarine ausprobieren möchten.
        p Weitere Hintergründe zu submarine und wie es entstanden ist, finden Sie auf unserem #{link_to "Blog", 'http://blog.softwareinmotion.de'} oder auf #{link_to "Facebook", 'http://de-de.facebook.com/scrumbacklog'}
        p.contact_data Haben Sie noch Fragen? #{link_to "Kontaktieren Sie uns.", contact_page_path}
      span
        | &nbsp;
javascript:
  $(function() {
    //highlight current navigation link
    $lnk = $("#navigation a[href='" + window.location.href + "']");
    $lnk.addClass("active");
  });