config/routes.rb
Submarine::Application.routes.draw do
  resources :questions

  if feature_active? :persist_present_demo
    root :to => 'navigation#index', :as => 'index'
    get 'contact_page' => 'questions#new', :as => 'contact_page'
  else
    root :to => 'issues#new_issues_list', :as => 'index'
    get 'contact_page' => 'navigation#contact_page', :as => 'contact_page'
  end
  post 'change_list' => 'issues#change_list', :as => 'change_list'
  post 'finish_issue/:id' => 'issues#finish_issue', :as => 'finish_issue'
  post 'activate_issue/:id' => 'issues#activate_issue', :as => 'activate_issue'
  get 'finished_issues' => 'issues#finished_issues_list', :as => 'finished_issues'

  get 'new_issues' => 'issues#new_issues_list', :as => 'new_issues'

  get 'impressum' => 'navigation#impressum', :as => 'impressum'
  get 'finished'=> 'questions#finished', :as => 'finished'

  put 'issues/:id' => 'issues#status_handler', :as => 'status_handler'

  resources :issues do
    member { get 'file_attachment' }
  end
  resources :projects do
    member { get 'project_icon' }
  end
  resources :bugs, :controller => 'issues'
  resources :tasks, :controller => 'issues'
  resources :user_stories, :controller => 'issues'
  resources :document, :controller => 'issues'
end

app/views/layouts/_footer.html.slim
p*{'style' => "clear:both; min-height: 8ex;"}
	| &nbsp;
footer
	div.center
		div.menu-left
		div.menu-right
			- feature_active? :persist_present_demo do
				span
					= link_to 'Impressum', impressum_path
		div.menu-center
			span
				| powered by
				= link_to 'http://www.softwareinmotion.de' do
					= image_tag 'swim_logo.png'
				= link_to 'http://www.softwareinmotion.de' do
					= " softwareinmotion"

app/views/layouts/application.html.slim
doctype html
html
  head
    title Submarine
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = javascript_include_tag "swimbox.js"
    = csrf_meta_tags

    meta name="msvalidate.01" content="EC7C55357265A423945004A6731B561E"

    = favicon_link_tag

  body
    javascript:
      $(document).ready(SWIMBOX.init);
    header
      div.center
        div.menu-left
          = link_to index_path do
            = image_tag "logo.png", :id => "logo"
        div.menu-right
          div.stack
            div.wrapper
              div.content
                div#navigation
                  = render_navigation :renderer => :links
                - if feature_active? :persist_present_demo
                  | <a href="https://github.com/softwareinmotion/submarine"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub"></a>
        div.menu-center
          - feature_active? :persist_present_demo do
            | <h1>Demo</h1>
      noscript
        p Bitte aktivieren Sie JavaScript, um die volle Funktionalität von submarine verwenden zu können.
    div#page-content
      - flash.each do |name, msg|
        = content_tag :div, msg, id: "flash#{name}"
      = yield
    = render :partial => "layouts/footer"

app/views/layouts/navigation.html.slim
doctype html
html
  head
    title Submarine
    = stylesheet_link_tag "navigation", "questions"
    = javascript_include_tag "navigation"
    = javascript_include_tag "swimbox.js"
    = csrf_meta_tags

    meta name="msvalidate.01" content="EC7C55357265A423945004A6731B561E"
    = favicon_link_tag
    | <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

  body
    javascript:
      $(document).ready(SWIMBOX.init);
    header
      div.center
        div.menu-left
          = link_to index_path do
            = image_tag "logo.png", :id => "logo"
        div.menu-right
          div.stack
            div.wrapper
              div.content
                div#navigation
                  = render_navigation :renderer => :links
                | <a href="https://github.com/softwareinmotion/submarine"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub"></a>
    - flash.each do |name, msg|
      = content_tag :div, msg, id: "flash#{name}"

    = yield

    = render :partial => "layouts/footer"

app/views/layouts/questions.html.slim
doctype html
html
  head
    title Submarine
    = stylesheet_link_tag "navigation", "questions"
    = javascript_include_tag "navigation"
    = csrf_meta_tags
    meta name="msvalidate.01" content="EC7C55357265A423945004A6731B561E"
    = favicon_link_tag

  body
    header
      = link_to index_path do
        = image_tag "logo.png", :id => "logo"
    - flash.each do |name, msg|
      = content_tag :div, msg, id: "flash#{name}"
    = yield

    = render :partial => "layouts/footer"